### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by godofecht** [TurbulenceDev/Turbulence#11]
If so...

I'd love to contribute and add WebAudio support. (AND VST support for audio -> I want to use my vocal compressor)

**Comment by exp111** [comment]
Hi, thanks for the interest!

Unless discord changed something big, it should still work. Ripcord still works after 3 years of no updates…

I'd suggest you try it out on a test account first but I havent heard of anyone being banned unless you're doing specific stuff like joining servers or opening new dms. 

I've started implementing voice chat in a branch (vc?) but only did the initial vc start messages and not the real webrtc stuff

**Comment by godofecht** [comment]
You free for 15-20 minutes just to run through some queries?

**Comment by exp111** [comment]
> You free for 15-20 minutes just to run through some queries?

Sure add me on discord exp111
